"""empty message

Revision ID: 99a6d55cb74f
Revises: 
Create Date: 2018-07-26 14:17:45.492099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99a6d55cb74f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='ab_permission')
    op.drop_table('ab_permission')
    op.drop_index('name', table_name='company')
    op.drop_index('property_name', table_name='company')
    op.drop_table('company')
    op.drop_index('name', table_name='ab_role')
    op.drop_table('ab_role')
    op.drop_index('name', table_name='property')
    op.drop_table('property')
    op.drop_index('user_id', table_name='ab_user_role')
    op.drop_table('ab_user_role')
    op.drop_index('username', table_name='ab_register_user')
    op.drop_table('ab_register_user')
    op.drop_index('email', table_name='ab_user')
    op.drop_index('username', table_name='ab_user')
    op.drop_table('ab_user')
    op.drop_index('permission_view_id', table_name='ab_permission_view_role')
    op.drop_table('ab_permission_view_role')
    op.drop_index('name', table_name='ab_view_menu')
    op.drop_table('ab_view_menu')
    op.drop_index('permission_id', table_name='ab_permission_view')
    op.drop_table('ab_permission_view')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_permission_view',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('view_menu_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['ab_permission.id'], name='ab_permission_view_ibfk_1'),
    sa.ForeignKeyConstraint(['view_menu_id'], ['ab_view_menu.id'], name='ab_permission_view_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('permission_id', 'ab_permission_view', ['permission_id', 'view_menu_id'], unique=True)
    op.create_table('ab_view_menu',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'ab_view_menu', ['name'], unique=True)
    op.create_table('ab_permission_view_role',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('permission_view_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_view_id'], ['ab_permission_view.id'], name='ab_permission_view_role_ibfk_1'),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], name='ab_permission_view_role_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('permission_view_id', 'ab_permission_view_role', ['permission_view_id', 'role_id'], unique=True)
    op.create_table('ab_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('login_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fail_login_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('changed_on', mysql.DATETIME(), nullable=True),
    sa.Column('created_by_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], name='ab_user_ibfk_2'),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], name='ab_user_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'ab_user', ['username'], unique=True)
    op.create_index('email', 'ab_user', ['email'], unique=True)
    op.create_table('ab_register_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('registration_date', mysql.DATETIME(), nullable=True),
    sa.Column('registration_hash', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'ab_register_user', ['username'], unique=True)
    op.create_table('ab_user_role',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], name='ab_user_role_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], name='ab_user_role_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'ab_user_role', ['user_id', 'role_id'], unique=True)
    op.create_table('property',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('popularity', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('district', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('area', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('availability', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'property', ['name'], unique=True)
    op.create_table('ab_role',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'ab_role', ['name'], unique=True)
    op.create_table('company',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('property_name', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('room', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('property_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], name='company_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('property_name', 'company', ['property_name'], unique=True)
    op.create_index('name', 'company', ['name'], unique=True)
    op.create_table('ab_permission',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'ab_permission', ['name'], unique=True)
    # ### end Alembic commands ###
